# Generated by Django 3.0.7 on 2020-06-28 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='img',
            field=models.CharField(max_length=100),
        ),
    ]
